### PR TITLE
Remove generator dependency completely

### PR DESCRIPTION
**Pull request by dcermak**
This finishes the work done in 58d56e98ea903a2db4924764a174ebcbc3848e8a

### CODE REVIEW

**Comment by monora** [comment]
@dcermak Thanks for finding this and your PR in RGL. I will create new releases for your changes soon.

**Comment by dcermak** [comment]
Thank you very much @monora!

**Comment by dcermak** [comment]
> @dcermak Thanks for finding this and your PR in RGL. I will create new releases for your changes soon.

I don't want to rush you @monora, but do you have an ETA? (Just asking, there's no really rush)

**Comment by monora** [comment]
Oh, thank you for the reminder. I just forgot to push the tag and release. The gem had already been publish in August :-(
https://rubygems.org/gems/stream

**Comment by dcermak** [comment]
No worries and thanks for the info!

**Pull request merged**
